#!/bin/bash


## do this for headset ###
if [ "$1" == "hs" ]; then
    echo """pcm.!default {
type hw
card 2
}

defaults.ctl.card 2
defaults.pcm.card 2
defaults.timer.card 2
""" > $HOME/.asoundrc

sudo /etc/init.d/alsa-utils restart
/usr/sbin/alsactl init 2

elif [ "$1" == "sp" ]; then
    echo """pcm.!default {
type hw
card 0
}

defaults.ctl.card 0
defaults.pcm.card 0
defaults.timer.card 0
""" > $HOME/.asoundrc

sudo /etc/init.d/alsa-utils restart
/usr/sbin/alsactl init 0



elif [ "$1" == "1" ]; then
    echo """pcm.!default {
type hw
card 1
}

defaults.ctl.card 1
defaults.pcm.card 1
defaults.timer.card 1
""" > $HOME/.asoundrc

sudo /etc/init.d/alsa-utils restart
/usr/sbin/alsactl init 1

else
    echo "usage: chaudout [hs|sp]"
fi