#!/bin/sh
    
lynx -dump -nolist 'http://dict.leo.org/ende?lp=ende&lang=de&searchLoc=0&cmpType=relaxed&sectHdr=on&spellToler=on&search='"$1"'&relink=on' | grep '\[ \]' | grep $1 | sed 's/   \[ \]    //' | sed 's/  /    <==>   /'