#!/bin/bash

find . \( -name "#*#" -o -name "*~" \) -print
echo -n "remove? "
read answer

if [ "$answer" == "y" ]; then
    find . \( -name "#*#" -o -name "*~" \) | xargs rm
    echo "done"
else
    echo "NOT deleting anything"
fi

