#!/bin/bash

echo 'nameserver 8.8.8.8' > /etc/resolv.conf
#echo 'nameserver 192.168.66.1' > /etc/resolv.conf
#echo 'nameserver 8.26.56.26' > /etc/resolv.conf
#echo 'nameserver 156.154.70.22' >> /etc/resolv.conf