#!/bin/bash

# test root
if [[ $UID -ne 0 ]]; then
    echo "don't try this without superuser powers"
    exit 1
fi

# check arguments
if [ "$1" == "-h" ]; then
    echo "usage: shrinet [in out]"
    echo "ex: shrinet eth0 eth1"
    echo "def: shrinet eth0 wlan0"
    exit 0
fi

if [ "$_" == "3" ]; then
    OUT=$2
    IN=$1
else
    OUT="wlan0"
    IN="eth0"
fi

# check interfaces

if [ -n "`ifconfig | grep $OUT`" ]; then
    echo "OUT Interface $OUT is up"
else
    echo "OUT Interface $OUT is down"
    echo "...bringing up $OUT"
    ifconfig $OUT up
    echo "...$OUT is up now, you probably want to get some internet connection there"
fi

if [ -n "`ifconfig | grep $IN`" ]; then
    echo "IN Interface $IN is up"
else
    echo "IN Interface $IN is down"
    echo "...bringing up $IN"
    ifconfig $IN up
    echo "...#IN is up now, you probably want to set up a network connection"
fi


# iptable set up for share
echo "enable ip forwarding"
echo 1 > /proc/sys/net/ipv4/ip_forward

echo "setting up masquerading"
iptables -A FORWARD -o $OUT -i $IN -j ACCEPT
iptables -A POSTROUTING -t nat -j MASQUERADE

echo "done"
exit 0