#!/bin/bash

# jollyroger flag
JOL=0

# colors
RED="\e[31m"
BLUE="\e[34m"
DEFAULT="\e[0m"

# interface
IF="wlan0"

if [ -e ~/.wifisec ]; then
    while read line; do
	eval ${line}
    done < ~/.wifisec
else
    echo 'Warning: no password file found'
fi


if [ '$essid' == '' ]; then
    echo -n "essid? "
    read essid
    echo -n "pw? "
    read pw
fi


echo "checking if ap exists: $essid"
ifconfig $IF up
string=$(iwlist $IF scan | grep "$essid")
if [ -n "$string" ]; then
    echo -e $BLUE"connecting to $RED$essid$BLUE...$DEFAULT"
    
    # get the interface down
    ifconfig $IF down
    
    # release the dhcp lease
    dhclient -r $IF 

    # configure wpa support
    echo -e $BLUE"wpa_supplicant: $DEFAULT"
    wpa_passphrase "$essid" "$pw" > /etc/wpa_supplicant.conf
    wpa_supplicant -d -B -i $IF -Dwext -c /etc/wpa_supplicant.conf

    # start the interface
    ifconfig $IF up

    # set the interface into managed mode
    iwconfig $IF mode Managed

    # request ip
    echo -e $BLUE"dhclient: $DEFAULT"
    dhclient -v $IF
    dhc_ex_cd=$?

    if [ $dhc_ex_cd -eq "0" ]; then
	cowsay "Muh, Connected to $essid"
    else
	cowsay "Muh, Connecting failed :("
	exit
    fi

    # set name server
    echo -n "" > /etc/resolv.conf
    if [ $JOL == 1 ]; then
	echo "nameserver 192.168.66.10" >> /etc/resolv.conf
    fi
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
else
    echo -e $RED"Error:$DEFAULT ap not available"
fi