#!/bin/bash

# set program to run
prog=$1

# set timing options
if [ $# -ge 2 ]; then 
    time=$2
else
    echo "Using default time 00:00:00"
    time=00:00:00
fi

if [ $# -ge 3 ]; then
    timetorun=$3
else
    echo "No timetorun specified, won't stop."
fi
#    echo -n "Using current day: "
#    echo $(date +"%a %d.")

# calc start and finish time
goal=$(date --date="$(date +"%a %b %d") $time $(date +"%Z %Y")" +%s)
start=$(date +%s)

tleft=`expr $goal - $start`

if [ $tleft -lt 0 ]; then
    echo "Error: time passed already."
    exit
fi

# sleep until the time has come
sleep $tleft

# run the program in background
$prog &

sleep $timetorun

progname=$(echo $prog | cut -d " " -f1)
if [ "$progname" = "sudo" ]; then
    progname=$(echo $prog | cut -d " " -f2)
fi

sudo pkill -x $progname
